In [75]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/heart.csv')
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [76]:
df.columns

Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [77]:
from scipy.stats import zscore
numerical_cols = ['Age','RestingBP','Cholesterol','FastingBS','MaxHR','Oldpeak']
z_scores = np.abs(df[numerical_cols].apply(zscore))
df_filtered = df[(z_scores < 3).all(axis=1)]
print(f"Original dataset size: {df.shape[0]} rows")
print(f"Filtered dataset size: {df_filtered.shape[0]} rows")
df_filtered.to_csv("cleaned_data.csv", index=False)

Original dataset size: 918 rows
Filtered dataset size: 899 rows

In [78]:
df_filtered.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [79]:
df_filtered['ChestPainType'].unique()
df_filtered['ST_Slope'].unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [80]:
df_filtered['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [81]:
from sklearn.preprocessing import LabelEncoder
df1 = df_filtered.copy()
label_encoder = LabelEncoder()
df1['Sex'] = label_encoder.fit_transform(df1['Sex'])
df1['ExerciseAngina'] = label_encoder.fit_transform(df1['ExerciseAngina'])
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,ATA,140,289,0,Normal,172,0,0.0,Up,0
1,49,0,NAP,160,180,0,Normal,156,0,1.0,Flat,1
2,37,1,ATA,130,283,0,ST,98,0,0.0,Up,0
3,48,0,ASY,138,214,0,Normal,108,1,1.5,Flat,1
4,54,1,NAP,150,195,0,Normal,122,0,0.0,Up,0

In [82]:
chest_pain_mapping = {'TA': 0, 'ATA': 1, 'NAP': 2, 'ASY': 3}
resting_ecg_mapping = {'Normal': 0, 'ST': 1, 'LVH': 2}
st_slope_mapping = {'Up': 0, 'Flat': 1, 'Down': 2}
df1['ChestPainType'] = df['ChestPainType'].map(chest_pain_mapping)
df1['RestingECG'] = df['RestingECG'].map(resting_ecg_mapping)
df1['ST_Slope'] = df['ST_Slope'].map(st_slope_mapping)

In [83]:
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,0,172,0,0.0,0,0
1,49,0,2,160,180,0,0,156,0,1.0,1,1
2,37,1,1,130,283,0,1,98,0,0.0,0,0
3,48,0,3,138,214,0,0,108,1,1.5,1,1
4,54,1,2,150,195,0,0,122,0,0.0,0,0

In [84]:
print(type(df1))

<class 'pandas.core.frame.DataFrame'>

In [85]:
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,0,172,0,0.0,0,0
1,49,0,2,160,180,0,0,156,0,1.0,1,1
2,37,1,1,130,283,0,1,98,0,0.0,0,0
3,48,0,3,138,214,0,0,108,1,1.5,1,1
4,54,1,2,150,195,0,0,122,0,0.0,0,0

In [86]:
X = df1.drop("HeartDisease",axis='columns')
y = df1.HeartDisease

X.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,1,1,140,289,0,0,172,0,0.0,0
1,49,0,2,160,180,0,0,156,0,1.0,1
2,37,1,1,130,283,0,1,98,0,0.0,0
3,48,0,3,138,214,0,0,108,1,1.5,1
4,54,1,2,150,195,0,0,122,0,0.0,0

In [92]:
y.head()

0    0
1    1
2    0
3    1
4    0
Name: HeartDisease, dtype: int64

In [87]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_scaled = scalar.fit_transform(X)
X_scaled

array([[-1.42815446,  0.515943  , -1.33939022, ..., -0.8229452 ,
        -0.85546862, -1.04249607],
       [-0.47585532, -1.93819859, -0.26524945, ..., -0.8229452 ,
         0.13751561,  0.62216462],
       [-1.7455875 ,  0.515943  , -1.33939022, ..., -0.8229452 ,
        -0.85546862, -1.04249607],
       ...,
       [ 0.3706328 ,  0.515943  ,  0.80889133, ...,  1.21514774,
         0.33611246,  0.62216462],
       [ 0.3706328 , -1.93819859, -1.33939022, ..., -0.8229452 ,
        -0.85546862,  0.62216462],
       [-1.63977649,  0.515943  , -0.26524945, ..., -0.8229452 ,
        -0.85546862, -1.04249607]])

In [91]:
print(type(X_scaled))

<class 'numpy.ndarray'>

In [88]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=30)

In [89]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train, y_train)
svm_model.score(X_test,y_test)

0.8333333333333334

In [93]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
rf_model.score(X_test,y_test)

0.85

In [94]:
lr_model = LogisticRegression()
lr_model.fit(X_train, y_train)
lr_model.score(X_test,y_test)

0.8388888888888889

In [97]:
from sklearn.decomposition import PCA
pca = PCA(0.95)
X_pca = pca.fit_transform(X)

In [98]:
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, y, test_size=0.2, random_state=30)

In [99]:
svm_model = SVC(kernel='linear', random_state=42)
svm_model.fit(X_train_pca, y_train)
svm_model.score(X_test_pca,y_test)

0.6666666666666666

In [100]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train_pca, y_train)
rf_model.score(X_test_pca,y_test)

0.6277777777777778

In [101]:
lr_model = LogisticRegression()
lr_model.fit(X_train_pca, y_train)
lr_model.score(X_test_pca,y_test)

0.6666666666666666